import type { Metadata } from 'next'
import './globals.css'
import Header from '../components/molecules/header'
import { overlock } from './fonts'

export const metadata: Metadata = {
  title: 'Franzis fabelhafte Törtchen',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de-DE" className={overlock.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
